<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BuyerSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['kode_buyer' => 'A20', 'nama_buyer' => 'POLRI'],
            ['kode_buyer' => 'A2F', 'nama_buyer' => 'PT BENTARA SINAR PRIMA'],
            ['kode_buyer' => 'A2K', 'nama_buyer' => 'CV TANDIKA JAYA LESTARI'],
            ['kode_buyer' => 'A2K', 'nama_buyer' => 'PT AGUNG NIAGA NUSANTARA'],
            ['kode_buyer' => 'A2K', 'nama_buyer' => 'PT EIGERINDO'],
            ['kode_buyer' => 'A2P', 'nama_buyer' => 'PT PASIFIK KREASI PRIMAJAYA'],
            ['kode_buyer' => 'A2P', 'nama_buyer' => 'PT VISTA MANDIRI'],
            ['kode_buyer' => 'A2Q', 'nama_buyer' => 'PT GRETCHEN MULTI SANDANG BRAND MR D.I.Y'],
            ['kode_buyer' => 'A2Q', 'nama_buyer' => 'PT GRETCHEN MULTI SANDANG GARMEN'],
            ['kode_buyer' => 'A2Q', 'nama_buyer' => 'PT GRETCHEN MULTI SANDANG'],
            ['kode_buyer' => 'A2Q', 'nama_buyer' => 'PT GRETCHEN SANDANG GARMEN'],
            ['kode_buyer' => 'A2R', 'nama_buyer' => 'PT COLORINDO INTERNUSA'],
            ['kode_buyer' => 'A2S', 'nama_buyer' => 'PT ALFA CITRA SEJAHTERA'],
            ['kode_buyer' => 'A31', 'nama_buyer' => 'ADIDAS'],
            ['kode_buyer' => 'A32', 'nama_buyer' => 'ADIDAS'],
            ['kode_buyer' => 'A34', 'nama_buyer' => 'ADIDAS'],
            ['kode_buyer' => 'A35', 'nama_buyer' => 'ADIDAS'],
            ['kode_buyer' => 'A38', 'nama_buyer' => 'ADIDAS'],
            ['kode_buyer' => 'A39', 'nama_buyer' => 'ADIDAS'],
            ['kode_buyer' => 'A3R', 'nama_buyer' => 'ROYCE TOO'],
            ['kode_buyer' => 'A3V', 'nama_buyer' => 'VICTORIA SECRET'],
            ['kode_buyer' => 'A44', 'nama_buyer' => 'ADIDAS'],
            ['kode_buyer' => 'A4Z', 'nama_buyer' => 'LC WAIKIKI'],
            ['kode_buyer' => 'A54', 'nama_buyer' => 'HUNTER'],
            ['kode_buyer' => 'A5A', 'nama_buyer' => 'HUNTER'],
            ['kode_buyer' => 'A5F', 'nama_buyer' => 'PLUSOCKS'],
            ['kode_buyer' => 'A5F', 'nama_buyer' => 'OKAMOTO'],
            ['kode_buyer' => 'A5P', 'nama_buyer' => 'OKAMOTO'],
            ['kode_buyer' => 'A5V', 'nama_buyer' => 'OKAMOTO'],
            ['kode_buyer' => 'S07', 'nama_buyer' => 'DANIEL SANTOSO'],
            ['kode_buyer' => 'S08', 'nama_buyer' => 'ELBERT WIJAYA'],
            ['kode_buyer' => 'S08', 'nama_buyer' => 'ELBERT WIJAYA / S07 DANIEL SANTOSO'],
            ['kode_buyer' => 'S08', 'nama_buyer' => 'ELBERT'],
            ['kode_buyer' => 'S08', 'nama_buyer' => 'LOKAL-ELBERT WIJAYA'],
            ['kode_buyer' => 'S08', 'nama_buyer' => 'SAHID JAYA PUTRA'],
            ['kode_buyer' => 'S08', 'nama_buyer' => 'YUNALDI'],
            ['kode_buyer' => 'S1M', 'nama_buyer' => 'AMSCAN'],
            ['kode_buyer' => 'S2D', 'nama_buyer' => 'AUCHAN'],
            ['kode_buyer' => 'S2H', 'nama_buyer' => 'CIH'],
            ['kode_buyer' => 'S2Z', 'nama_buyer' => 'H&M'],
            ['kode_buyer' => 'S3T', 'nama_buyer' => 'FASHION UK'],
            ['kode_buyer' => 'S41', 'nama_buyer' => 'MIZUNO'],
            ['kode_buyer' => 'S41', 'nama_buyer' => 'OKAMOTO'],
            ['kode_buyer' => 'S4K', 'nama_buyer' => '& S4Z KAUFLAND & LIDL'],
            ['kode_buyer' => 'S4K', 'nama_buyer' => 'KAUFLAND'],
            ['kode_buyer' => 'S4Y', 'nama_buyer' => 'LIDL'],
            ['kode_buyer' => 'S4Z', 'nama_buyer' => 'LIDL'],
            ['kode_buyer' => 'S51', 'nama_buyer' => 'C&A'],
            ['kode_buyer' => 'S5I', 'nama_buyer' => 'C&A CHILDREN'],
            ['kode_buyer' => 'S5I', 'nama_buyer' => 'C&A KIDS'],
            ['kode_buyer' => 'S61', 'nama_buyer' => 'C&A BABY'],
            ['kode_buyer' => 'S61', 'nama_buyer' => 'C&A LADIES + MEN'],
            ['kode_buyer' => 'S61', 'nama_buyer' => 'C&A LADIES'],
            ['kode_buyer' => 'S61', 'nama_buyer' => 'C&A MEN'],
            ['kode_buyer' => 'S61', 'nama_buyer' => 'C&A NEW BORN'],
            ['kode_buyer' => 'S61', 'nama_buyer' => 'C&A'],
            ['kode_buyer' => 'S61', 'nama_buyer' => 'H&M CHILDREN'],
            ['kode_buyer' => 'S76', 'nama_buyer' => 'H&M'],
            ['kode_buyer' => 'S8C', 'nama_buyer' => 'H&M'],
            ['kode_buyer' => 'S8Q', 'nama_buyer' => 'GO SPORT'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'LOKAL'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'PT KRINA DUTA'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'PT PRIMA SANDANG MULIA'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'ANDRI ASLAMI'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'CLIFF MARCEL'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'CV SUNFLOWER KALIBRE'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'KK KARYAWAN'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'KK SATPAM'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'LOKAL - CLIFF MARCELL'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'LOKAL - YONATAN'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'LOKAL PT SOKA'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'LOKAL UMUM'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'LOKAL YUNALDI'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'PT AGUNG NIAGA NUSANTARA'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'PT HERSO TICEP INDONESIA'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'PT PRIMA SANDANG MULIA'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'PT PRIMA SANDANG'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'SAHID JAYA P'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'TNI KEMHAN'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'YONATAN'],
            ['kode_buyer' => 'S95', 'nama_buyer' => 'YUNALDI'],
            ['kode_buyer' => 'SC2', 'nama_buyer' => 'WIBRA'],
            ['kode_buyer' => 'SC3', 'nama_buyer' => 'KIK'],
            ['kode_buyer' => 'SH4', 'nama_buyer' => 'ERGEE'],
            ['kode_buyer' => 'SI9', 'nama_buyer' => 'STADIUM'],
            ['kode_buyer' => 'T1B', 'nama_buyer' => 'C&A LADIES'],
        ];

        $this->db->table('master_buyer')->insertBatch($data);
    }
}
