<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MasterRangePemesananRosso extends Seeder
{
    public function run()
    {
        $data = [
            // SENIN
            [
                'days' => 'Monday',
                'area' => 'ROSSO_KK1',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'ROSSO_KK2',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'ROSSO_KK5',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'ROSSO_KK7',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'ROSSO_KK8',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'ROSSO_KK11',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            // SELASA
            [
                'days' => 'Tuesday',
                'area' => 'ROSSO_KK1',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'ROSSO_KK2',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'ROSSO_KK5',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'ROSSO_KK7',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'ROSSO_KK8',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'ROSSO_KK11',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            // RABU
            [
                'days' => 'Wednesday',
                'area' => 'ROSSO_KK1',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'ROSSO_KK2',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'ROSSO_KK5',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'ROSSO_KK7',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'ROSSO_KK8',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'ROSSO_KK11',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            // KAMIS
            [
                'days' => 'Thursday',
                'area' => 'ROSSO_KK1',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'ROSSO_KK2',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'ROSSO_KK5',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'ROSSO_KK7',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'ROSSO_KK8',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'ROSSO_KK11',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            // JUMAT
            [
                'days' => 'Friday',
                'area' => 'ROSSO_KK1',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'ROSSO_KK2',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'ROSSO_KK5',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'ROSSO_KK7',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'ROSSO_KK8',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'ROSSO_KK11',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 1,
            ],
            // SABTU
            [
                'days' => 'Saturday',
                'area' => 'ROSSO_KK1',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'ROSSO_KK2',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'ROSSO_KK5',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'ROSSO_KK7',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'ROSSO_KK8',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'ROSSO_KK11',
                'range_spandex' => 0,
                'range_karet' => 0,
                'range_benang' => 0,
                'range_nylon' => 2,
            ],
        ];
        // Using Query Builder
        $this->db->table('master_range_pemesanan')->insertBatch($data);
    }
}
