<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MasterRangePemesanan extends Seeder
{
    public function run()
    {
        $data = [
            // SENIN
            [
                'days' => 'Monday',
                'area' => 'KK1A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK1B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK2A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK2B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK2C',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK5G',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK7K',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK7L',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK8D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK8F',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK8J',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK9D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK10',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Monday',
                'area' => 'KK11M',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],

            // SELASA
            [
                'days' => 'Tuesday',
                'area' => 'KK1A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK1B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK2A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK2B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK2C',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK5G',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK7K',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK7L',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK8D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK8F',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK8J',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK9D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK10',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Tuesday',
                'area' => 'KK11M',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],

            // RABU
            [
                'days' => 'Wednesday',
                'area' => 'KK1A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK1B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK2A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK2B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK2C',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK5G',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK7K',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK7L',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK8D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK8F',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK8J',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK9D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK10',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Wednesday',
                'area' => 'KK11M',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],

            // KAMIS
            [
                'days' => 'Thursday',
                'area' => 'KK1A',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK1B',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK2A',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK2B',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK2C',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK5G',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK7K',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK7L',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK8D',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK8F',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK8J',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK9D',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK10',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Thursday',
                'area' => 'KK11M',
                'range_spandex' => 2,
                'range_karet' => 2,
                'range_benang' => 1,
                'range_nylon' => 1,
            ],

            // JUMAT
            [
                'days' => 'Friday',
                'area' => 'KK1A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK1B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK2A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK2B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK2C',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK5G',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK7K',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK7L',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK8D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK8F',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK8J',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK9D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK10',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],
            [
                'days' => 'Friday',
                'area' => 'KK11M',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 2,
                'range_nylon' => 1,
            ],

            // SABTU
            [
                'days' => 'Saturday',
                'area' => 'KK1A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK1B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK2A',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK2B',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK2C',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK5G',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK7K',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK7L',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK8D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK8F',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK8J',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK9D',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK10',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
            [
                'days' => 'Saturday',
                'area' => 'KK11M',
                'range_spandex' => 1,
                'range_karet' => 1,
                'range_benang' => 1,
                'range_nylon' => 2,
            ],
        ];

        // Using Query Builder
        $this->db->table('master_range_pemesanan')->insertBatch($data);
    }
}
